# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import service_order_pb2 as service__order__pb2


class OrderServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetOrders = channel.unary_unary(
        '/OrderService/GetOrders',
        request_serializer=service__order__pb2.GetOrdersRequest.SerializeToString,
        response_deserializer=service__order__pb2.GetOrdersResponse.FromString,
        )


class OrderServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetOrders(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_OrderServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetOrders': grpc.unary_unary_rpc_method_handler(
          servicer.GetOrders,
          request_deserializer=service__order__pb2.GetOrdersRequest.FromString,
          response_serializer=service__order__pb2.GetOrdersResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'OrderService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
