# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_order.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_order.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13service_order.proto\":\n\x10GetOrdersRequest\x12\x12\n\npage_index\x18\x01 \x01(\x05\x12\x12\n\npage_count\x18\x02 \x01(\x05\"+\n\x11GetOrdersResponse\x12\x16\n\x06orders\x18\x01 \x03(\x0b\x32\x06.Order\"z\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\x04\x12\r\n\x05title\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x03\x12\x13\n\x0b\x63reate_time\x18\x06 \x01(\t\x12\x13\n\x0bupdate_time\x18\x07 \x01(\t2D\n\x0cOrderService\x12\x34\n\tGetOrders\x12\x11.GetOrdersRequest\x1a\x12.GetOrdersResponse\"\x00\x62\x06proto3')
)




_GETORDERSREQUEST = _descriptor.Descriptor(
  name='GetOrdersRequest',
  full_name='GetOrdersRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page_index', full_name='GetOrdersRequest.page_index', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_count', full_name='GetOrdersRequest.page_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=81,
)


_GETORDERSRESPONSE = _descriptor.Descriptor(
  name='GetOrdersResponse',
  full_name='GetOrdersResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='orders', full_name='GetOrdersResponse.orders', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=126,
)


_ORDER = _descriptor.Descriptor(
  name='Order',
  full_name='Order',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Order.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='Order.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='Order.user_id', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='title', full_name='Order.title', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='Order.price', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='create_time', full_name='Order.create_time', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='update_time', full_name='Order.update_time', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=250,
)

_GETORDERSRESPONSE.fields_by_name['orders'].message_type = _ORDER
DESCRIPTOR.message_types_by_name['GetOrdersRequest'] = _GETORDERSREQUEST
DESCRIPTOR.message_types_by_name['GetOrdersResponse'] = _GETORDERSRESPONSE
DESCRIPTOR.message_types_by_name['Order'] = _ORDER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetOrdersRequest = _reflection.GeneratedProtocolMessageType('GetOrdersRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETORDERSREQUEST,
  __module__ = 'service_order_pb2'
  # @@protoc_insertion_point(class_scope:GetOrdersRequest)
  ))
_sym_db.RegisterMessage(GetOrdersRequest)

GetOrdersResponse = _reflection.GeneratedProtocolMessageType('GetOrdersResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETORDERSRESPONSE,
  __module__ = 'service_order_pb2'
  # @@protoc_insertion_point(class_scope:GetOrdersResponse)
  ))
_sym_db.RegisterMessage(GetOrdersResponse)

Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), dict(
  DESCRIPTOR = _ORDER,
  __module__ = 'service_order_pb2'
  # @@protoc_insertion_point(class_scope:Order)
  ))
_sym_db.RegisterMessage(Order)



_ORDERSERVICE = _descriptor.ServiceDescriptor(
  name='OrderService',
  full_name='OrderService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=252,
  serialized_end=320,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetOrders',
    full_name='OrderService.GetOrders',
    index=0,
    containing_service=None,
    input_type=_GETORDERSREQUEST,
    output_type=_GETORDERSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ORDERSERVICE)

DESCRIPTOR.services_by_name['OrderService'] = _ORDERSERVICE

# @@protoc_insertion_point(module_scope)
